service: mutante-ms

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  timeout: 10
  memorySize: 512

functions:
  hello:
    handler: handler.hello
  mutant:
    handler: src/mutant/handler.Handler
    description: Microservice for 
    events:
      - http:
          path: /v1/isMutant
          method: post
          cors: true
          integration: lambda
          response: ${self:custom.customHeaders}

custom:
    customHeaders:
      headers:
        Content-Type: "'application/json'"
        Content-Security-Policy: "'Include default-src 'self''"
        X-Frame-Options: "'DENY'"
        X-Content-Type-Options: "'nosniff'"
        X-Permitted-Cross-Domain-Policies: "'none'"
        Strict-Transport-Security: "'max-age=31536000; includeSubDomains; preload'"
        X-XSS-Protection: "'1'"
        Cache-Control: "'max-age=0; Expires=-1 or Expires: Fri, 01 Jan 1990 00:00:00 GMT; no-cache, must-revalidate'"
      statusCodes:
          200:
              pattern: ''
          400:
              pattern: '.*"code":400.*'
              template: "$input.path('$.errorMessage')"
          401:
              pattern: '.*"code":401.*'
              template: "$input.path('$.errorMessage')"
          404:
              pattern: '.*"code":404.*'
              template: "$input.path('$.errorMessage')"
          422:
              pattern: '.*"code":422.*'
              template: "$input.path('$.errorMessage')"
          500:
              pattern: '.*"code":500.*'
              template: "$input.path('$.errorMessage')"
    logRetentionInDays: 14
    optimize:
      global: true