service: mutante-ms

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  timeout: 10
  memorySize: 512

functions:
  hello:
    handler: handler.hello
  mutant:
    handler: src/mutant/handler.Handler
    description: Microservice for 
    events:
      - http:
          path: /v1/isMutant
          method: post
          cors: true
          integration: lambda